[workspace]
resolver = "3"
members = [
    "crates/bromium", 
    "crates/screen-capture", 
    "crates/uitree",
]

[workspace.dependencies]
uiautomation = "0.18.0"
chrono = "0.4.41"

[profile.release-with-debug]
inherits = "release"
debug = true