[package]
name = "bromium"
version = "0.4.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bromium"
crate-type = ["cdylib"]

[dependencies]
uiautomation.workspace = true
chrono.workspace = true
windows.workspace = true
log.workspace = true

# uiautomation = "0.18.0"
# chrono = "0.4.41"
# windows = { version = "0.61.1", features = ["Win32_Graphics_Gdi", "Win32_Foundation", "Win32_UI_HiDpi", "Win32_UI_WindowsAndMessaging"] }

screen-capture = { path = "../screen-capture" }
uitree = { path = "../uitree" }
xmlutil = { path = "../xmlutil" }

pyo3 = "0.25.1"

regex = "1.5"
winapi = { version = "0.3", features = ["winuser"] } # used by app_control.rs
winnow = "0.7.9"
display-info = "0.5.4"
fs_extra = "1.3.0"


