[package]
name = "screen-capture"
version = "0.1.0"
edition = "2024"
description = "Screen Cappture is a MS Windows screen capture library written in Rust."
license = "Apache-2.0"
documentation = ""
homepage = ""
repository = ""
keywords = ["screen", "monitor", "window", "capture", "image"]

# [workspace]
# members = ["."]
# resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
image = ["image/default"]

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
log = "0.4"
scopeguard = "1.2"
thiserror = "2.0"

[target.'cfg(target_os = "windows")'.dependencies]
widestring = "1.2"
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_Devices_Display",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Storage_Xps",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
    "Win32_Storage_FileSystem",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi_Common",
] }


[dev-dependencies]
fs_extra = "1.3"

[target.'cfg(target_os="windows")'.dev-dependencies]
windows = { version = "0.61", features = ["Win32_UI_HiDpi"] }
