[package]
name = "uitree"
version = "0.1.0"
edition = "2024"

[dependencies]
uiautomation.workspace = true
chrono.workspace = true
log.workspace = true

xmlutil = { path = "../xmlutil" }

# quick-xml = "0.38.0"

# [profile.release]
# opt-level = 3
# lto = true
# debug = true